### ISSUE TITLE
[2.0] Breaks HTTP access to history or welcome page depending on how is started

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy-kubernetes#25]
I'm trying the new 2.0 chart spec with a completely PhenoMeNal agnostic setup. If I set ingress to false , without changing any other defaults, it shows the following error in red on the Galaxy main page:

```
{
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36",
  "onLine": true,
  "version": "18.05",
  "xhr": {
    "readyState": 4,
    "responseText": "{\"err_msg\": \"History is not accessible by user\", \"err_code\": 403002}",
    "responseJSON": {
      "err_msg": "History is not accessible by user",
      "err_code": 403002
    },
    "status": 403,
    "statusText": "Forbidden"
  },
  "options": {
    "parse": true,
    "data": "keys=size%2Cnon_ready_jobs%2Ccontents_active%2Chid_counter",
    "emulateHTTP": false,
    "emulateJSON": false,
    "textStatus": "error",
    "errorThrown": "Forbidden"
  },
  "url": "http://192.168.99.100:30700/galaxy/api/histories/f2db41e1fa331b3e?keys=size%2Cnon_ready_jobs%2Ccontents_active%2Chid_counter",
  "model": {
    "model_class": "History",
    "id": "f2db41e1fa331b3e",
    "name": "Unnamed history",
    "state": "new",
    "deleted": false,
    "contents_active": {
      "active": 0,
      "deleted": 0,
      "hidden": 0
    },
    "contents_states": {},
    "hid_counter": 1,
    "update_time": "2018-07-10T08:52:30.118Z",
    "user_id": null,
    "importable": false,
    "tags": [],
    "contents_url": "/galaxy/api/histories/f2db41e1fa331b3e/contents",
    "slug": null,
    "username_and_slug": null,
    "url": "/galaxy/api/histories/f2db41e1fa331b3e",
    "genome_build": "?",
    "create_time": "2018-07-10T08:52:30.118Z",
    "published": false,
    "annotation": null,
    "size": 0,
    "purged": false,
    "nice_size": "(empty)"
  },
  "user": {
    "id": null,
    "username": "(anonymous user)",
    "total_disk_usage": 0,
    "nice_total_disk_usage": "0 bytes",
    "quota_percent": null,
    "is_admin": false
  }
}
```
This happens regardless of whether you try to access Galaxy on `/galaxy` or without a prefix. When you access on `/galaxy`, the errors above show an additional `/galaxy` added (so you see some `/galaxy/galaxy`. We never had such behaviour on 1.x.

If I then change my helm config to use ingress.path to an empty value, I get a different, apparently less severe error:

```
{
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36",
  "onLine": true,
  "version": "18.05",
  "xhr": {
    "readyState": 4,
    "responseText": "<html>\r\n  <head><title>Not Found</title></head>\r\n  <body>\r\n    <h1>Not Found</h1>\r\n    <p>The resource could not be found.\r\n<br/>No route for /galaxy/api/histories/1cd8e2f6b131e891\r\n<!--  --></p>\r\n    <hr noshade>\r\n    <div align=\"right\">WSGI Server</div>\r\n  </body>\r\n</html>\r\n",
    "status": 404,
    "statusText": "Not Found"
  },
  "options": {
    "parse": true,
    "data": "keys=size%2Cnon_ready_jobs%2Ccontents_active%2Chid_counter",
    "emulateHTTP": false,
    "emulateJSON": false,
    "textStatus": "error",
    "errorThrown": "Not Found"
  },
  "url": "http://192.168.99.100:30700/galaxy/api/histories/1cd8e2f6b131e891?keys=size%2Cnon_ready_jobs%2Ccontents_active%2Chid_counter",
  "model": {
    "model_class": "History",
    "id": "1cd8e2f6b131e891",
    "name": "Unnamed history",
    "state": "new",
    "deleted": false,
    "contents_active": {
      "active": 0,
      "deleted": 0,
      "hidden": 0
    },
    "contents_states": {},
    "hid_counter": 1,
    "update_time": "2018-07-10T08:56:16.700Z",
    "user_id": null,
    "importable": false,
    "tags": [],
    "contents_url": "/galaxy/api/histories/1cd8e2f6b131e891/contents",
    "slug": null,
    "username_and_slug": null,
    "url": "/galaxy/api/histories/1cd8e2f6b131e891",
    "genome_build": "?",
    "create_time": "2018-07-10T08:56:16.700Z",
    "published": false,
    "annotation": null,
    "size": 0,
    "purged": false,
    "nice_size": "(empty)"
  },
  "user": {
    "id": null,
    "username": "(anonymous user)",
    "total_disk_usage": 0,
    "nice_total_disk_usage": "0 bytes",
    "quota_percent": null,
    "is_admin": false
  }
}
```

This is accessing the URL without any prefix. Notice that the contents URLs still have the "/galaxy" part. I wonder if there is some config of the containers involved as well.

I created this deploy with this helm config:

```
# Settings for the init image
init:
  image:
    repository: pcm32/galaxy-sc-tertiary-init
    tag: v18.05
    pullPolicy: Always
  force_copy: "__venv__,__config__,__galaxy-central__"

image:
  repository: pcm32/galaxy-web-k8s
  tag: v18.05
  pullPolicy: Always

admin:
  email: admin@email.co.uk
  password: "change-me"
  api_key: askdhaskjdhqwkdnqdq
  username: admin

galaxy_conf:
  admin_users: admin2@email.co.uk
  allow_user_creation: true
  allow_user_deletion: true

job_conf: {}

persistence:
  minikube:
    hostPath: "/data/galaxy-18.05-tertiary"

service:
  type: NodePort

ingress:
  enabled: false
  path: ""


postgresql:
  imageTag: "9.6.5_for_18.05"
  persistence:
    subPath: "postgres-tertiary"

proftpd:
  service:
    type: NodePort
```

Any ideas @nuwang? These containers where created from stock docker-galaxy-stable (master) and ansible-galaxy-extras on 18.05 plus an additional commit (https://github.com/pcm32/docker-galaxy-stable/tree/feature/k8s_container_building). Additional init simple places some config files for job conf, tool conf and tools.
